#########################################################################################
#
# Playbook to take mongodump of database
#
# How to execute:
# ansible-playbook -i inventory --extra-vars "db_name=<db_name>" playbook-mongodump.yml
#
# Author:       Anban Malarvendan
# License:      GNU GENERAL PUBLIC LICENSE Version 3 +
#               Section 7: Redistribution/Reuse of this code is permitted under the
#               GNU v3 license, as an additional term ALL code must carry the
#               original Author(s) credit in comment form.
#
#########################################################################################

- name: "mongodump | Playbook to backup {{ db_name }}"
  hosts: mongo-aws-vm03
  tasks:
    - name: "mongodump | Validate if db_name is defined"
      assert:
        that:
          - db_name is defined
        fail_msg: "Action failed: db_name variable is undefined."
        success_msg: "db_name is {{ db_name }}"

    - name: "mongodump | Data uploader - Variables"
      set_fact:
        file_to_be_uploaded: "/tmp/mongodump_{{ db_name }}"

    - name: "mongodump | Create backup directory"
      file:
        path: "{{ file_to_be_uploaded }}"
        state: directory
      changed_when: false

    - name: "mongodump | Perform MongoDB backup"
      command: mongodump --db {{ db_name }} --out {{ file_to_be_uploaded }}
      changed_when: true
